<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?php echo $page_title; ?></title>
<style>
body {
	font-family:'Open Sans', Arial;
	font-size:14px; font-weight:normal!important;
	color:#000;
}
h1 {
	font-size:22px;
	color:#000;
	/*text-transform:uppercase;*/
	font-weight:normal;
	margin:0;
	/*border-bottom:1px solid #333;*/
	padding-bottom:5px;
}
h2 {
	font-size:16px;
	text-align:center;
	/*text-transform:uppercase;*/
	color:#000;
	font-weight:normal;
	margin:0;
}

h3 {
	font-size:16px;
	/*text-transform:uppercase;*/
	color:#000;
	font-weight:normal;
	margin:0;
}

td {
	padding:4px 2px;
	border-top:0px solid #dfdfdf;
	border-bottom:0px solid #dfdfdf;
	border-collapse:collapse;
	font-weight:normal;
}
.table-bor td {
	border:1px solid #ddd;
	border-collapse:collapse;
	
}

.table-bor th{ padding:4px 0px;}
thead {
	font-size:14px;
	color:#000;
	
	background-color:#ccc;
}
thead th {
	height:auto;
	padding:5px 0px;
	font-size:14px;
	font-weight:bold;
	color:#000;
	background-color:#ccc;
}
table thead tr.odd td{font-size:12px;}
table tr.odd td {
	background-color: #f3f3f3;
	border-bottom: 1px solid #ddd; 	
	padding: 8px 2px;
}
table tr.even td {
	background-color: #ffffff;
	border-bottom: 1px solid #ddd;
	padding: 8px 2px;
}
.grey_bg {
	background-color:#ccc;
}
.grey_bg2 {
	background-color:#f9f9f9;
	border:1px solid #ddd;
}
.pd-tp{ padding:4px 0px;}
.pd-tp2{ padding:10px 0px;}
</style>
<?php /* ?>
<style>
 @font-face {
    font-family: kruti;
    src: url(http://bankeauction.com/bankeauc/fonts/k010.TTF);
}
 .hindi{font-family:'kruti'; font-size:18px; color:#000;}
 
  @font-face {
    font-family: AnjaliOldLipi;
    src: url(http://bankeauction.com/bankeauc/fonts/AnjaliOldLipi.ttf);
}
 .hindi_new{font-family:'AnjaliOldLipi'; font-size:18px; color:#000;}
</style>
<?php */ ?>
</head>

<body>
    <table width="980" border="0" align="center" cellpadding="0" cellspacing="0" style="background:#fff;">
        <tr>
            <td align="center" valign="top" scope="col"><img width="266" src="<?php echo base_url(); ?>bankeauc/assets/img/logo.png"></td>
        </tr>
            <tr><td colspan="2"></td></tr>	
    </table>

    <table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" style="background:#fff;">
        <tr class="odd">
            <td align="center" valign="top" scope="col"><h2> &nbsp;Scroll for Bank</h2></td>    
        </tr>
    </table>
    <p><strong style="padding-bottom: 5px;">Activity :</strong> E-Auction</p>
    <p><strong style="padding-bottom: 5px;">Property Address:</strong> <?php echo $auction_details->PropertyDescription; ?></p>
    <p><strong style="padding-bottom: 5px;">Dispose Order No.:</strong> <?php echo $sRefundData[0]->dispose_order_no; ?></p>
    <table  width="100%" border="0" align="left" cellpadding="0" cellspacing="0" class="table-bor" >
        <tbody role="alert" aria-live="polite" aria-relevant="all">
            <tr class="even">
                <td width="20%" align="left" valign="top" class=""><strong>Generated By  : </strong></td>
                <td width="30%" align="left" valign="top" class="">
                    <?php 
                        $first_name = GetTitleByField('tbl_user','id='.$sRefundData[0]->user_id,'first_name');
                        $last_name = GetTitleByField('tbl_user','id='.$sRefundData[0]->user_id,'last_name');
                        $full_name = $first_name." ".$last_name;
                        echo $full_name; 
                    ?>
                </td>

                <td width="20%" align="left" valign="top" class=""><strong>Emp No. :  </strong></td>
                <td width="30%" align="left" valign="top" class=""><?php echo $sRefundData[0]->user_id; ?></td>
            </tr>								
            <tr class="even">
                <td width="20%" align="left" valign="top" class=""><strong>Account to be  Debited  :   </strong></td>
                <td width="30%" align="left" valign="top" class=""><?php echo $sRefundData[0]->remitter_account_no; ?></td>
                <td width="20%" align="left" valign="top" class=""><strong> Bank Name  :  </strong></td>
                    <?php // echo number_format($auctionData[0]->reserve_price, 2).'/ '.$price_unit; ?>
                        <?php// echo moneyFormatIndia($total_amount_payable); ?>
                <td width="30%" align="left" valign="top" class=""> <?php echo $sRefundData[0]->remitter_bank_name; ?></td>

            </tr>
            <tr class="even">
                <td width="20%" align="left" valign="top" class=""><strong>IFSC Code  :   </strong></td>
                <td width="30%" align="left" valign="top" class=""><?php echo $sRefundData[0]->remitter_ifsc_code; ?></td>
                <td width="20%" align="left" valign="top" class=""><strong>Sequence Number  : </strong></td>
                <td width="30%" align="left" valign="top" class=""><?php echo $sRefundData[0]->cheque_no; ?></td>
            </tr>
            <tr class="even">
                <td width="20%" align="left" valign="top" class=""><strong>Sequence Date  :   </strong></td>
                <td width="30%" align="left" valign="top" class=""><?php echo date('d-m-Y',strtotime($sRefundData[0]->cheque_date)); ?></td>

                <td width="20%" align="left" valign="top" class=""><strong>Amount  :  </strong></td>
                <td width="30%" align="left" valign="top" class=""><?php echo $sRefundData[0]->total_amt; ?></td>
            </tr>
        </tbody>
    </table>
    <br><br>
    
    <table width="100%" border="0" align="left" cellpadding="0" cellspacing="0" class="mytable dataTable table-bor" id="big_table" aria-describedby="big_table_info">

        <thead>
            <tr class="odd" style="border-top:solid 1px #ccc;">
                <td width="5%" align="left" valign="top" class=""><strong>S/No.</strong></td>
                <td width="5%" align="left" valign="top" class=""><strong>Purpose</strong></td>
                <td width="15%" align="left" valign="top" class=""><strong>Sequence_no</strong></td>
                <td width="10%" align="left" valign="top" class=""><strong>Payorder No.</strong></td>						
                <td width="15%" align="left" valign="top" class=""><strong>Beneficiary Name</strong></td>
                <td width="15%" align="left" valign="top" class=""><strong>Account Number</strong></td>
                <td width="10%" align="left" valign="top" class=""><strong>IFSC Code </strong></td>
                <td width="10%" align="left" valign="top" class=""><strong>Amount (Rs.)</strong></td>
            </tr>
        </thead>
        <tbody role="alert" aria-live="polite" aria-relevant="all">
        <?php 
            if(count($sRefundData))
            {
                foreach($sRefundData as $key => $rData)
                { ?>       
                    <tr class="even">
                        <td align="left" valign="top" class=""><?php echo ++$key; ?></td>
                           <td width="5%" align="left" valign="top" class="">Refund of EMD</td>
                        <td  align="left" valign="top" class=""><?php echo $rData->sequence_no; ?></td>
                        <td align="left" valign="top" class=""><?php echo $rData->payorder_no; ?></td>
                        <td  align="left" valign="top" class=""><?php echo (($rData->receiver_name == '')? '--': $rData->receiver_name); ?></td>
                        <td align="left" valign="top" class=""><?php echo  ((($rData->receiver_account_no == '') OR ($rData->receiver_account_no == 0))? '--': $rData->receiver_account_no); ?></td>
                        <td  align="left" valign="top" class=""><?php echo (($rData->receiver_ifsc_code == '')? '--': $rData->receiver_ifsc_code); ?></td>
                        <td  align="left" valign="top" class=""><?php echo $rData->emd_to_be_refunded; ?></td>
                    </tr>
       <?php   } ?>
                    <tr class="odd">
                        <td  align="right" valign="top" class="" colspan="7"><strong>Total:</strong></td>
                        <td  align="left" valign="top" class=""><?php echo $sRefundData[0]->total_amt; ?></td>
                    </tr>
       
     <?php } ?>
	</tbody>             
    </table>
    <table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" style="background:#fff; margin-top:100px;">
        <tr>
            <td align="left" valign="top"><?php
            echo "Created On: " . date("d-m-Y h:i:sA");
            ?></td>
            <td align="right" valign="top" >(Signature and Seal of Paying Authoritie(s))</td>
        </tr>
    </table>
	
<!--
<br/><br/><br/><br/>
<div style="text-align:center;">
*************************Report Ended*************************
</div>
<br/><br/>
<div style="text-align:center;">
Disclaimer: This is a system generated report hence does not need any signature.
</div>
<div style="text-align:center;font-size:11px;position:absolute;bottom:20px; left: 0px;">
	<i>jda.com © Copyright <?php //echo date('Y');?> Jaipur Development Authority - All Rights Reserved</i>
	<hr/>
	<span>
		<i>Plot No. 301, First Floor, Udyog Vihar, Phase - 2, Gurgaon (HR)-122015, Tel: +91-124-4302020 Fax: +91-124-4302010 www.c1india.com</i>
	</span>
</div>
-->
</body>
</html>
