<div class="container-fluid container_margin">
            <div class="row row_bg">
               <div class="container">
                <div class="col-sm-12">
                    <div class="breadcrumb_main">
                        <ol class="breadcrumb">
                            <li><a href="<?php echo base_url();?>">Home</a></li>
                            <li class="active">Terms &amp; Conditions</li>
                        </ol>
<!--                        <h3>Bank Auctions in Amritsar</h3>-->
                    </div><!--breadcrumb_main-->
                </div>
            </div>
            </div><!--row-->
        </div><!--container-fluid-->
           <div class="container-fluid">
               <div class="row ad_row_width">
                   <div class="col-sm-12">
                       <h3 class="premium_service">Terms &amp; Conditions</h3>
                   </div>
               </div>
           </div>
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="about_us_main faq_main privacy_policy">
                        <div class="privacy_policy_inner">
                            <h4></h4>
                            <p>This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures. </p>
                        </div>
                        <div class="privacy_policy_inner">
                            <h4>User Agreement</h4>
                            <p>Your use of https://www.AuctionOnClick.com {including https://www.AuctionOnClick.com (hereinafter referred to as "AuctionOnClick") and its related sites, services and tools} is governed by the following terms and conditions. If you transact on any AuctionOnClick website other than the Website, you shall be subject to the policies that are applicable to the AuctionOnClick sites for such transaction. This User Agreement for the Website shall come into effect from the time and date the user accepts the same ("User Agreement"). You are contracting with C1 India Private Limited, a company incorporated under Companies Act, 1956 with registered office at 1502, 15th Floor, Ambadeep Building, 14, K. G. Marg, New Delhi- 110001. These terms and conditions constitute your binding obligations towards the contracting entity (hereinafter referred to as "C1 India"). </p>
                        </div>
                        <div class="privacy_policy_inner">
                            <h4>Amendments</h4>
                            <p>https://www.AuctionOnClick.com may amend this User Agreement and/or AuctionOnClick Rules and Policies at any time by posting a revised version on the Website. If the revised version of this User Agreement includes a Substantial Change, https://www.AuctionOnClick.com will provide you with prior notice of such Substantial Change/s. You are advised to regularly check for any amendments or updates to the terms and conditions contained in this User Agreement and in AuctionOnClick Rules and Policies.</p>
                            <p><strong>ACCESSING, BROWSING OR OTHERWISE USING THE SITE INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING. </strong></p>
                            <p>By impliedly or expressly accepting these Terms of Use, You also accept and agree to be bound by 'C1 India' Policies ((including but not limited to Privacy Policy available on /s/privacy policy) as amended from time to time.</p>
                            <p>The following terminology applies to these Terms and Conditions, Privacy Statement and Disclaimer Notice and all Agreements: "Client", "You" and "Your" refers to you, the person log on this website and compliant to the Company's terms and conditions. "The Company", "Ourselves", "We", "Our" and "Us", refers to our Company. "Party", "Parties", or "Us", refers to both the Client and ourselves. All terms refer to the offer, acceptance and consideration of payment necessary to undertake the process of our assistance to the Client in the most appropriate manner for the express purpose of meeting the Client's needs in respect of provision of the Company's stated services, in accordance with and subject to, prevailing law of India. Any use of the above terminology or other words in the singular, plural, capitalization and/or he/she or they, are taken as interchangeable and therefore as referring to same.</p>
                        </div>
                        <div class="privacy_policy_inner">
                            <h4>Terms & Conditions:</h4>
                            <p>Though all efforts have been made to ensure the accuracy of the content on this website, the same should not be construed as a statement of law or used for any legal purposes. In case of any ambiguity or doubts, users are advised to verify / check with C1 India to obtain appropriate professional advice.</p>
                            <p>Under no circumstances will C1 India be liable for any expense, loss or damage including, without limitation, indirect or consequential loss or damage, or any expense, loss or damage whatsoever arising from use, or loss of use, of data, arising out of or in connection with the use of this website.</p>
                        </div>
                        <div class="privacy_policy_inner">
                            <h4>Website Visit data</h4>
                            <p>This website records your visit and logs the following information for statistical purposes -your server's address; the name of the top-level domain from which you access the Internet (for example, .gov, .com, .in, etc.); the type of browser you use; the date and time you access the site; the pages you have accessed and the documents downloaded and the previous Internet address from which you linked directly to the site.</p>
							<p>We will not identify users or their browsing activities, except when a law enforcement agency may exercise a warrant to inspect the service provider's logs.</p>
                        </div>
                        <div class="privacy_policy_inner">
                            <h4>Modification of Portal</h4>
                            <p>C1 India reserves the rights to modify, add, delete and/or change the contents and classification and presentation of the information on the portal at any time as it may in its absolute discretion find to be expedient and without giving any notice. The modificationwould be done by C1 India. It is the user's responsibility to refer to the terms and/or any change or addition to the same while accessing the site.</p>
                        </div>
                        <div class="privacy_policy_inner">
                            <h4>System Requirements</h4>
                            <p>It is user's responsibility to comply with the system requirements: hardware, software, and Internet connectivity at user premises to access AuctionOnClick portal. C1 India is not responsible for non-compliance for the above by user.</p>
                        </div>
						<div class="privacy_policy_inner">
                            <h4>Cookies</h4>
                            <p>We employ the use of cookies. By accessing AuctionOnClick, you agreed to use cookies in agreement with the AuctionOnClick's Privacy Policy.</p>
                            <p>Most interactive websites use cookies to let us retrieve the user's details for each visit. Cookies are used by our website to enable the functionality of certain areas to make it easier for people visiting our website. Some of our affiliate/advertising partners may also use cookies.</p>
                        </div>
						<div class="privacy_policy_inner">
                            <h4>License</h4>
                            <p>Unless otherwise stated, AuctionOnClick and/or its licensors own the intellectual property rights for all material on AuctionOnClick. All intellectual property rights are reserved. You may access this from AuctionOnClick for your own personal use subjected to restrictions set in these terms and conditions.</p>
							<p>You must not:</p>
							<ul>
                                <li>Republish material from AuctionOnClick</li>
                                <li>Sell, rent or sub-license material from AuctionOnClick</li>
                                <li>Reproduce, duplicate or copy material from AuctionOnClick and redistribute content from AuctionOnClick</li>
                            </ul>
							<p>This Agreement shall begin on the date hereof.</p>
							<p>Parts of this website offer an opportunity for users to post and exchange opinions and information in certain areas of the website. AuctionOnClick does not filter, edit, publish or review Comments prior to their presence on the website. Comments do not reflect the views and opinions of AuctionOnClick,its agents and/or affiliates. Comments reflect the views and opinions of the person who post their views and opinions. To the extent permitted by applicable laws, AuctionOnClick shall not be liable for the Comments or for any liability, damages or expenses caused and/or suffered as a result of any use of and/or posting of and/or appearance of the Comments on this website.</p>
							<p>AuctionOnClick reserves the right to monitor all Comments and to remove any Comments which can be considered inappropriate, offensive or causes breach of these Terms and Conditions.</p>
							<p>You warrant and represent that:</p>
							<ul>
                                <li>You are entitled to post the Comments on our website and have all necessary licenses and consents to do so;</li>
                                <li>The Comments do not invade any intellectual property right, including without limitation copyright, patent or trademark of any third party;</li>
                                <li>The Comments do not contain any defamatory, libelous, offensive, indecent or otherwise unlawful material which is an invasion of privacy</li>
								<li>The Comments will not be used to solicit or promote business or custom or present commercial activities or unlawful activity.</li>
                            </ul>
							<p>You hereby grant AuctionOnClick a non-exclusive license to use, reproduce, edit and authorize others to use, reproduce and edit any of your Comments in any and all forms, formats or media.</p>
                        </div>
						<div class="privacy_policy_inner">
                            <h4>Linking to our Content</h4>
                            <p>The following organizations may link to our Website without prior written approval:</p>
							<ul>
                                <li>Government agencies;</li>
                                <li>Search engines;</li>
                                <li>News organizations;</li>
								<li>Online directory distributors may link to our Website in the same manner as they hyperlink to the Websites of other listed businesses; and</li>
								<li>System wide Accredited Businesses except soliciting non-profit organizations, charity shopping malls, and charity fundraising groups which may not hyperlink to our Web site..</li>
                            </ul>
                            <p>These organizations may link to our home page, to publications or to other Website information so long as the link: (a) is not in any way deceptive; (b) does not falsely imply sponsorship, endorsement or approval of the linking party and its products and/or services; and (c) fits within the context of the linking party's site.</p>
                            <p>We may consider and approve other link requests from the following types of organizations:</p>
							<ul>
                                <li>commonly-known consumer and/or business information sources;</li>
                                <li>dot.com community sites;</li>
                                <li>associations or other groups representing charities;</li>
								<li>online directory distributors;</li>
								<li>internet portals;</li>
								<li>accounting, law and consulting firms; and</li>
								<li>educational institutions and trade associations.</li>
                            </ul>
                            <p>We will approve link requests from these organizations if we decide that: (a) the link would not make us look unfavorably to ourselves or to our accredited businesses; (b) the organization does not have any negative records with us; (c) the benefit to us from the visibility of the hyperlink compensates the absence of AuctionOnClick; and (d) the link is in the context of general resource information.</p>
                            <p>These organizations may link to our home page so long as the link: (a) is not in any way deceptive; (b) does not falsely imply sponsorship, endorsement or approval of the linking party and its products or services; and (c) fits within the context of the linking party's site.</p>
                            <p>If you are one of the organizations listed in paragraph 2 above and are interested in linking to our website, you must inform us by sending an e-mail to AuctionOnClick(support@auctiononclick.com). Please include your name, your organization name, contact information as well as the URL of your site, a list of any URLs from which you intend to link to our Website, and a list of the URLs on our site to which you would like to link. Wait 2-3 weeks for a response.</p>
                            <p>Approved organizations may hyperlink to our Website as follows:</p>
                            <ul>
								<li>By use of our corporate name; or</li>
								<li>By use of the uniform resource locator being linked to; or</li>
								<li>By use of any other description of our Website being linked to that makes sense within the context and format of content on the linking party's site.</li>
							</ul>
							<p>No use of AuctionOnClick's logo or other artwork will be allowed for linking absent a trademark license agreement.</p>
                        </div>
						<div class="privacy_policy_inner">
                            <h4>iFrames</h4>
                            <p>Without prior approval and written permission, you may not create frames around our Webpages that alter in any way the visual presentation or appearance of our Website.</p>
                        </div>
						<div class="privacy_policy_inner">
                            <h4>User Conduct</h4>
                            <p>You agree that all information, data, text, software, photographs, graphics, messages or other materials ("Content"), whether publicly posted or privately transmitted, are the sole responsibility of the person from which such Content originated. This means that you are entirely responsible for all Content that you upload, post, e-mail or otherwise transmit via the AuctionOnClick portal. C1 India does not control the Content posted via the AuctionOnClick portal and, as such, does not guarantee the accuracy, integrity or quality of such Content. Under no circumstances will C1 India be liable in any way for any Content, including, but not limited to, for any errors or omissions in any Content, or for any loss or damage of any kind incurred as a result of the use of any Content posted, e-mailed or otherwise transmitted via the Site. Special Admonitions for International Use Recognizing the global nature of the Internet, you agree to comply with all local rules regarding online conduct and acceptable Content. Specifically, you agree to comply with all applicable laws regarding the transmission of technical data to and from India or the country in which you reside.</p>
                        </div>
						<div class="privacy_policy_inner">
                            <h4>Content Liability</h4>
                            <p>We shall not be hold responsible for any content that appears on your Website. You agree to protect and defend us against all claims that is rising on your Website. No link(s) should appear on any Website that may be interpreted as libelous, obscene or criminal, or which infringes, otherwise violates, or advocates the infringement or other violation of, any third party rights.</p>
                        </div>
						<div class="privacy_policy_inner">
                            <h4>Privacy Policy: </h4>
                            <p>As a general rule, this website does not collect Personal Information about you when you visit the site. You can generally visit the site without revealing Personal Information, unless you choose to provide such information.Please refer "Privacy Policy".</p>
                        </div>
						<div class="privacy_policy_inner">
                            <h4>Reservation of Rights</h4>
                            <p>We reserve the right to request that you remove all links or any particular link to our Website. You approve to immediately remove all links to our Website upon request. We also reserve the right to amend these terms and conditions and it's linking policy at any time. By continuously linking to our Website, you agree to be bound to and follow these linking terms and conditions.</p>
                        </div>
						<div class="privacy_policy_inner">
                            <h4>Removal of links from our website</h4>
                            <p>If you find any link on our Website that is offensive for any reason, you are free to contact and inform us any moment. We will consider requests to remove links but we are not obligated to or so or to respond to you directly.</p>
                            <p>We do not ensure that the information on this website is correct, we do not warrant its completeness or accuracy; nor do we promise to ensure that the website remains available or that the material on the website is kept up to date.</p>
                        </div>
						<div class="privacy_policy_inner">
                            <h4>Disclaimer</h4>
                            <p>AuctionOnClick.com website makes no warranty, expressed or implied, as to the results obtained from the use of the information on the website.</p>
                            <p>AuctionOnClick.com shall have no liability for the accuracy of the information and cannot be held liable for any third-party claims or losses of any damages, the user are advised to confirm the information by visiting the bank/branch/property concerned.</p>
                            <p>The information contained in this web site does not constitute a confirmed offer to sell or the solicitation of an offer to buy any property or service; and should not be treated as recommendation in connection with any investment decision.</p>
                            <p>AuctionOnClick.com website is not responsible for the contents of any linked site or any link contained in a linked site. The hypertext links provided herein are meant only as a convenience and the inclusion of any link does not imply endorsement by of the referenced site.</p>
							<p>To the maximum extent permitted by applicable law, we exclude all representations, warranties and conditions relating to our website and the use of this website. Nothing in this disclaimer will:</p>
							<ul>
							<li>limit or exclude our or your liability for death or personal injury;</li>
							<li>limit or exclude our or your liability for fraud or fraudulent misrepresentation;</li>
							<li>limit any of our or your liabilities in any way that is not permitted under applicable law; or</li>
							<li>exclude any of our or your liabilities that may not be excluded under applicable law.</li>
							</ul>
                            <p>The limitations and prohibitions of liability set in this Section and elsewhere in this disclaimer: (a) are subject to the preceding paragraph; and (b) govern all liabilities arising under the disclaimer, including liabilities arising in contract, in tort and for breach of statutory duty.</p>
                            <p>As long as the website and the information and services on the website are provided free of charge, we will not be liable for any loss or damage of any nature.</p>
                            <p>While surfing through this site you will come across directories and links to Government and Private Organizations. The contents of these sites are not to be construed as a responsibility of or endorsement by the Ministry and are owned by the respective organizations which may be contacted for any further information or suggestion.</p>
                        </div>
						<div class="privacy_policy_inner">
                            <h4>Subscription Cancellations & Refund Policy</h4>
                            <p>If you want to cancel a subscription you have with us, please mail us at support@auctiononclick.com</p>
                            <p>When you cancel a subscription with us, you will continue to receive your subscription benefits until the end of the current billing period. You will not receive a refund of any portion of the subscription fees you paid for the current or prior billing periods.</p>
                            <p>&nbsp;</p>
                            <p>Example 1: Quarterly subscription cancellation</p>
                            <p>If we process a quarterly subscription's cancellation on June 7th, you will continue to receive the benefits of that subscription until September 6th (90 days) and there will not be a refund of any part of the quarterly subscription fee. You will neither be billed for nor receive the benefits of the cancelled subscription after your current billing cycle ends.</p>
                            <p>&nbsp;</p>
                            <p>Example 2: Annual subscription cancellation</p>
                            <p>If we process an annual subscription's cancellation on the first day of the subscription that begins June 1, you will continue to receive the benefits of that subscription May 31st of the next year and there will not be a refund of any part of the annual subscription fee. You will neither be billed for nor receive the benefits of the cancelled subscription after your current billing cycle ends.</p>
							<p>Do not wait until the end of a billing or subscription period to make a subscription cancellation request because such requests are typically processed within 2 to 3 business days after we receive them. As it takes longer for us to receive postal mail than electronic mail, we recommend that you email your request. Providing us with your account/subscription number (if you have one) can also speed up the process of honoring your request.</p>
							<p>We will confirm your subscription has been cancelled by either email or postal mail.</p>
                        </div>
						<div class="privacy_policy_inner">
                            <h4>Confidentiality</h4>
                            <p>AuctionOnClick and the subscriber agree to keep all information submitted to the platform or which otherwise is disclosed by either party under this Agreement confidential and shall not disclose any such information to any third parties without the consent of the owner of the confidential information save that it can disclose such information to those of its employees, agents or professional advisers who have a need to know and who are bound to keep the information confidential.</p>
                            <p>AuctionOnClick and the subscriber agree to use the Confidential Information of the other solely in connection with the performance of the Event and not otherwise or for the benefit of any third party.</p>
                            <p>Each party will, at its own expense, take all reasonable and appropriate steps to enforce any duty of confidence owed to it by any party (including employees, agents, sub-contractors and professional advisors), insofar as such enforcement appears to be necessary for the protection of the confidentiality of the Confidential Information.</p>
                            <p>The provisions of Terms and condition will not apply to the whole or any part of the Confidential Information which:</p>
							<ul>
							<li>is lawfully obtained free of any duty of confidentiality otherwise than from a party to this Agreement </li>
							<li>is already in the other party's possession other than as a result of a breach;</li>
							<li> the Party can demonstrate is in the public domain;</li> 
							<li>is independently developed or acquired by that Party without access to the Confidential Information;</li> 
							<li>is disclosed pursuant to a judicial or other governmental order, provided that the Party required to disclose gives the other Party reasonable notice prior to such disclosure to allow the disclosing Party a reasonable opportunity to seek a protective order or equivalent; or</li>
							<li>Is disclosed with prior written consent of the other Party.</li>

							</ul>
                        </div>
						<div class="privacy_policy_inner">
                            <h4>Miscellaneous</h4>
                            <p>This Agreement shall all be governed and construed in accordance with the laws of India applicable to agreements made and to be performed in India. C1 India's failure to insist upon or enforce strict performance of any provision of this Agreement shall not be construed as a waiver of any provision or right. Neither the course of conduct between the parties nor trade practice shall act to modify any provision of this Agreement. C1 India may assign its rights and duties under this Agreement to any party at any time without notice to you. Any rights not expressly granted herein are reserved.</p>
                        </div>
						<div class="privacy_policy_inner">
                            <h4>Governing Law</h4>
                            <p>Terms shall be governed by, and construed in accordance with, Indian law. The parties irrevocably agree that the courts of Delhi shall (subject to the paragraph below) have exclusive jurisdiction to settle any dispute which may arise out of, under, or in connection with these Terms or the legal relationship established by them, and for those purposes irrevocably submit all disputes to the jurisdiction of the courts at Delhi, irrespective of whether Courts/Tribunals in other areas have concurrent or similar jurisdiction.</p>
                        </div>
						<div class="privacy_policy_inner">
                            <h4>Contacting Us</h4>
                            <p>Email your refund or subscription cancellation request to support@auctiononclick.com. Please include the words <strong>"Refund Request"</strong> or <strong>"Subscription Cancellation Request"</strong> in the subject line of your email.</p>
                            <p>To serve you and others better in the future, we request (but do not require) that you tell us why you want a refund or cancelled your subscription. We want satisfied customers.</p>
                        </div>
                    </div>
                </div>
            </div><!--row-->
        </div><!--container-->